spring.application.name=FinanceTracker
spring.data.mongodb.uri=mongodb://localhost:27017/financetracker
spring.data.mongodb.database=financetracker
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOU LITTLE NAUGHTY NAUGHTY ;)
spring.mail.password=YOU LITTLE NAUGHTY NAUGHTY ;)
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Your Groq key

groq.api.key=YOU LITTLE NAUGHTY NAUGHTY ;)
groq.model=llama-3.3-70b-versatile
groq.base.url=https://api.groq.com/openai/v1

